**PRAKHAR BHARDWAJ**


**24-787 ASSIGNMENT 2 **


ANDREW ID - prakharb

Question 2

In [70]:
import numpy as np 
import time as t
np.random.seed(24787)
a = np.random.randint(low = 0, high = 8, size = [3,4,4])
print(a)
a.shape
#print(a.index(4))
#for i,j in a:
#if j == 4:
  #  print(i)

[[[2 6 4 1]
  [0 4 4 3]
  [6 6 1 2]
  [7 0 6 5]]

 [[1 3 3 7]
  [4 7 2 5]
  [0 4 6 7]
  [5 5 7 1]]

 [[7 2 4 5]
  [6 7 7 0]
  [6 2 0 4]
  [2 0 7 6]]]


(3, 4, 4)

In [71]:
location = np.where(a==4)
#print("Depth Indices: ",location[0])
print("Row Indices: ",location[1])
print("Column Indices: ", location[2])

Row Indices:  [0 1 1 1 2 0 2]
Column Indices:  [2 1 2 0 1 2 3]


In [72]:
reps = (2,2)
b = np.tile(a,reps)
print(b)

[[[2 6 4 1 2 6 4 1]
  [0 4 4 3 0 4 4 3]
  [6 6 1 2 6 6 1 2]
  [7 0 6 5 7 0 6 5]
  [2 6 4 1 2 6 4 1]
  [0 4 4 3 0 4 4 3]
  [6 6 1 2 6 6 1 2]
  [7 0 6 5 7 0 6 5]]

 [[1 3 3 7 1 3 3 7]
  [4 7 2 5 4 7 2 5]
  [0 4 6 7 0 4 6 7]
  [5 5 7 1 5 5 7 1]
  [1 3 3 7 1 3 3 7]
  [4 7 2 5 4 7 2 5]
  [0 4 6 7 0 4 6 7]
  [5 5 7 1 5 5 7 1]]

 [[7 2 4 5 7 2 4 5]
  [6 7 7 0 6 7 7 0]
  [6 2 0 4 6 2 0 4]
  [2 0 7 6 2 0 7 6]
  [7 2 4 5 7 2 4 5]
  [6 7 7 0 6 7 7 0]
  [6 2 0 4 6 2 0 4]
  [2 0 7 6 2 0 7 6]]]


In [73]:
sum_along_depth = np.sum(b,axis=0)
print (sum_along_depth)
sum_along_depth.shape

[[10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]
 [10 11 11 13 10 11 11 13]
 [10 18 13  8 10 18 13  8]
 [12 12  7 13 12 12  7 13]
 [14  5 20 12 14  5 20 12]]


(8, 8)

In [74]:
np.random.seed(24787)
a=np.random.randint(low=0,high=8,size=[1000,1000])
b=np.random.randint(low=0,high=8,size=[1000,1000])
print("Matrix A")
print(a)
#print(len(a))
#print(len(a[0]))
print("Matrix B")
print(b)


Matrix A
[[2 6 4 ... 7 7 0]
 [0 0 7 ... 1 6 5]
 [1 4 5 ... 4 3 2]
 ...
 [1 7 0 ... 1 4 3]
 [4 1 0 ... 2 1 1]
 [2 0 6 ... 3 6 2]]
Matrix B
[[6 1 4 ... 2 3 0]
 [7 0 3 ... 0 0 1]
 [1 3 0 ... 3 5 2]
 ...
 [1 0 5 ... 4 5 0]
 [6 2 2 ... 5 7 2]
 [3 5 2 ... 0 2 6]]


In [79]:
def matmul(a,b):
    arr = np.zeros((1000,1000),dtype = int)
    t_start = t.time()
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                arr[i][j] += a[i][k] * b[k][j]
    t_end = t.time()
    print(arr)
    print("time taken = ", t_end - t_start)

matmul(a,b)
t_start_ = t.time()
c = a@b
t_end_ = t.time()
print(c)
print("Time taken = ", t_end_ - t_start_)

[[12146 12253 12302 ... 12123 12415 12239]
 [12251 12131 12180 ... 12691 12396 12497]
 [11434 11864 12043 ... 12348 11960 12207]
 ...
 [11774 11945 12276 ... 12339 12178 12059]
 [11627 12167 12254 ... 11929 11958 12078]
 [11560 12145 12077 ... 12210 12124 12031]]
time taken =  656.8271396160126
[[12146 12253 12302 ... 12123 12415 12239]
 [12251 12131 12180 ... 12691 12396 12497]
 [11434 11864 12043 ... 12348 11960 12207]
 ...
 [11774 11945 12276 ... 12339 12178 12059]
 [11627 12167 12254 ... 11929 11958 12078]
 [11560 12145 12077 ... 12210 12124 12031]]
Time taken =  0.8444726467132568


The inbuilt function is faster than the function used is because in the inbuilt function all the array multiplication would be computed at an instance while in our function the array multiplication is computed individually, thus increases the time